version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  build:
    executor:
      name: node/default
      tag: '14.11.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
      - run:
          command: yarn build
      - store_artifacts:
          path: ./dist

workflows:
  build:
    jobs:
      - build

